version: 2

build:
 os: "ubuntu-22.04"
 tools:
   python: "3.8"

python:
  install:
      - method: pip
        path: .
        extra_requirements:
          - rtd
      - requirements: docs/requirements-docs.txt

sphinx:
  builder: html
  fail_on_warning: true
