name: Publish

on:
  push:
    if: startsWith(github.ref, 'refs/heads/tags')

jobs:
  build:
    uses: ./.github/workflows/testing.yml
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Install twine to check the package
        run: pip install twine
      - name: Check the package
        run: twine check dist/*
      - name: Publish distribution 📦 to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
